# Generated by Django 5.2.17 on 2026-09-04 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dingtalk_dept_id', models.CharField(blank=True, db_comment='钉钉通讯录中的部门唯一标识；手工维护且未同步的部门可为空。', max_length=64, null=True, unique=True, verbose_name='钉钉部门标识')),
                ('name', models.CharField(db_comment='部门显示名称。', max_length=128, verbose_name='部门名称')),
                ('is_active', models.BooleanField(db_comment='停用后不再参与内容受众匹配与后台选择。', default=True, verbose_name='启用状态')),
                ('last_sync_at', models.DateTimeField(blank=True, db_comment='最近一次从钉钉同步该部门的时间。', null=True, verbose_name='最近同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='部门创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='部门最后更新时间。', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'accounts_department',
                'db_table_comment': '组织部门，支持父子层级，参与内容受众范围匹配。',
            },
        ),
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(db_comment='标记该部门是否为用户主部门；每个用户最多一个主部门。', default=False, verbose_name='是否主部门')),
                ('effective_at', models.DateTimeField(blank=True, db_comment='关系生效时间；空值表示自建立起生效。', null=True, verbose_name='生效时间')),
                ('expired_at', models.DateTimeField(blank=True, db_comment='关系失效时间；空值表示当前仍有效。', null=True, verbose_name='失效时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='关系创建时间。', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户部门关系',
                'verbose_name_plural': '用户部门关系',
                'db_table': 'accounts_user_department',
                'db_table_comment': '用户与部门的多对多关系；同一用户与同一部门仅一条记录，每用户最多一个主部门。',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='内容受众用户组显示名称。', max_length=128, unique=True, verbose_name='用户组名称')),
                ('description', models.TextField(blank=True, db_comment='用户组用途与成员范围说明。', default='', verbose_name='说明')),
                ('is_active', models.BooleanField(db_comment='停用后不再参与内容受众匹配与后台选择。', default=True, verbose_name='启用状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='用户组创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='用户组最后更新时间。', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '内容用户组',
                'verbose_name_plural': '内容用户组',
                'db_table': 'accounts_user_group',
                'db_table_comment': '知识内容受众用户组，仅用于内容可见范围；系统操作角色仍使用 Django Group。',
            },
        ),
        migrations.CreateModel(
            name='UserGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='成员加入时间。', verbose_name='加入时间')),
            ],
            options={
                'verbose_name': '用户组成员关系',
                'verbose_name_plural': '用户组成员关系',
                'db_table': 'accounts_user_group_membership',
                'db_table_comment': '用户与内容用户组的成员关系；同一用户与同一用户组仅一条记录。',
            },
        ),
        migrations.AlterModelTableComment(
            name='user',
            table_comment='平台用户，保存钉钉身份映射、员工信息与账号状态。',
        ),
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', '正常'), ('disabled', '已禁用'), ('departed', '已离职')], db_comment='平台账号状态：正常、已禁用或已离职。', default='active', max_length=20, verbose_name='账号状态'),
        ),
        migrations.AddField(
            model_name='user',
            name='dingtalk_corp_id',
            field=models.CharField(blank=True, db_comment='钉钉企业 corpId；未同步钉钉身份的用户为空。', max_length=64, null=True, verbose_name='钉钉企业标识'),
        ),
        migrations.AddField(
            model_name='user',
            name='dingtalk_union_id',
            field=models.CharField(blank=True, db_comment='钉钉跨应用人员标识，按授权能力保存，不作为主映射依据。', max_length=128, null=True, verbose_name='钉钉跨应用标识'),
        ),
        migrations.AddField(
            model_name='user',
            name='dingtalk_user_id',
            field=models.CharField(blank=True, db_comment='企业内钉钉员工标识，与钉钉企业标识组合构成唯一映射。', max_length=128, null=True, verbose_name='钉钉员工标识'),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, db_comment='员工真实姓名，来自钉钉通讯录或管理员维护。', default='', max_length=128, verbose_name='显示姓名'),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_no',
            field=models.CharField(blank=True, db_comment='公司员工编号；允许为空，由同步或后台维护更新。', max_length=64, null=True, verbose_name='员工编号'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, db_comment='最近一次从钉钉同步该用户信息的时间。', null=True, verbose_name='最近同步时间'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_status'], name='accounts_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('dingtalk_corp_id__isnull', False), ('dingtalk_user_id__isnull', False)), fields=('dingtalk_corp_id', 'dingtalk_user_id'), name='accounts_user_dingtalk_uniq'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_no__isnull', False)), fields=('employee_no',), name='accounts_user_empno_uniq'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, db_comment='上级部门；空值表示顶级部门。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounts.department', verbose_name='父部门'),
        ),
        migrations.AddField(
            model_name='userdepartment',
            name='department',
            field=models.ForeignKey(db_comment='用户所属部门。', on_delete=django.db.models.deletion.PROTECT, related_name='user_memberships', to='accounts.department', verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='userdepartment',
            name='user',
            field=models.ForeignKey(db_comment='所属用户。', on_delete=django.db.models.deletion.PROTECT, related_name='department_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='usergroupmembership',
            name='user',
            field=models.ForeignKey(db_comment='用户组成员。', on_delete=django.db.models.deletion.PROTECT, related_name='user_group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='usergroupmembership',
            name='user_group',
            field=models.ForeignKey(db_comment='用户所属的内容用户组。', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='accounts.usergroup', verbose_name='内容用户组'),
        ),
        migrations.AddConstraint(
            model_name='userdepartment',
            constraint=models.UniqueConstraint(fields=('user', 'department'), name='accounts_ud_user_dept_uniq'),
        ),
        migrations.AddConstraint(
            model_name='userdepartment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='accounts_ud_primary_uniq'),
        ),
        migrations.AddConstraint(
            model_name='usergroupmembership',
            constraint=models.UniqueConstraint(fields=('user', 'user_group'), name='accounts_ugm_user_group_uniq'),
        ),
    ]
