# Generated by Django 5.2.17 on 2026-09-04 14:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_department_userdepartment_usergroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(db_comment='文章主记录内部主键，使用 UUID，不直接暴露给员工。', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='文章 ID')),
                ('kb_no', models.CharField(db_comment='全局唯一且不可变的知识编号，格式为 KB-000001。', editable=False, max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='知识编号必须符合 KB-000001 格式。', regex='^KB-\\d{6}$')], verbose_name='知识编号')),
                ('title', models.CharField(db_comment='当前对外使用的文章标题；发布新版本时由服务层同步。', max_length=60, verbose_name='当前标题')),
                ('article_type', models.CharField(choices=[('troubleshooting', '故障处理'), ('guide', '操作指南'), ('sop', 'SOP'), ('case', '运维案例'), ('announcement', '通知公告'), ('faq', 'FAQ')], db_comment='文章表达模板与用途类型。', db_index=True, max_length=20, verbose_name='文章类型')),
                ('audience_policy', models.CharField(choices=[('all_employees', '全员'), ('restricted', '指定范围'), ('it_only', '仅 IT')], db_comment='文章受众策略摘要；具体允许和拒绝对象存入 kb_article_audience。', default='restricted', max_length=20, verbose_name='内容受众策略')),
                ('article_status', models.CharField(choices=[('active', '正常'), ('offline', '已下架'), ('archived', '已归档')], db_comment='文章主状态：正常、已下架或已归档。', db_index=True, default='active', max_length=20, verbose_name='文章状态')),
                ('effective_at', models.DateTimeField(blank=True, db_comment='文章计划生效时间；空值表示审核发布后立即生效。', null=True, verbose_name='生效时间')),
                ('review_due_at', models.DateTimeField(db_comment='知识负责人应在该时间前完成复审。', db_index=True, verbose_name='复审截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='文章主记录首次创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='文章主记录最后更新时间。', verbose_name='更新时间')),
                ('created_by', models.ForeignKey(db_comment='首次创建文章主记录的用户。', on_delete=django.db.models.deletion.PROTECT, related_name='created_articles', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('owner', models.ForeignKey(db_comment='负责知识准确性、更新和按期复审的用户。', on_delete=django.db.models.deletion.PROTECT, related_name='owned_articles', to=settings.AUTH_USER_MODEL, verbose_name='知识负责人')),
                ('updated_by', models.ForeignKey(db_comment='最后修改文章主记录的用户。', on_delete=django.db.models.deletion.PROTECT, related_name='updated_articles', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '知识文章',
                'verbose_name_plural': '知识文章',
                'db_table': 'kb_article',
                'db_table_comment': '知识文章主记录，保存稳定编号、生命周期状态和版本指针。',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.UUIDField(db_comment='文章版本内部主键，使用 UUID。', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='版本 ID')),
                ('version_no', models.PositiveIntegerField(db_comment='文章内从 1 开始递增的整数版本号。', verbose_name='版本号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('in_review', '待审核'), ('rejected', '已驳回'), ('published', '已发布'), ('superseded', '已替代')], db_comment='版本状态：草稿、待审核、已驳回、已发布或已替代。', db_index=True, default='draft', max_length=20, verbose_name='版本状态')),
                ('title', models.CharField(db_comment='该版本保存的标题快照。', max_length=60, verbose_name='版本标题')),
                ('summary', models.CharField(db_comment='搜索结果和详情页使用的文章摘要。', max_length=500, verbose_name='摘要')),
                ('applicable_scope', models.JSONField(blank=True, db_comment='结构化适用范围，例如系统、版本、设备、部门和网络环境。', default=dict, verbose_name='适用范围')),
                ('body', models.JSONField(blank=True, db_comment='由富文本编辑器生成的结构化正文 JSON，是版本内容的权威来源。', default=dict, verbose_name='结构化正文')),
                ('body_plaintext', models.TextField(blank=True, db_comment='从结构化正文提取的纯文本，用于检索、差异比较和后续 RAG。', verbose_name='正文纯文本')),
                ('change_summary', models.CharField(db_comment='作者说明本版本相对上一版本的主要修改。', max_length=500, verbose_name='版本说明')),
                ('submitted_at', models.DateTimeField(blank=True, db_comment='版本首次或最近一次提交审核的时间。', null=True, verbose_name='提交审核时间')),
                ('published_at', models.DateTimeField(blank=True, db_comment='该版本审核通过并正式发布的时间。', null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='版本记录创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='版本记录最后更新时间。', verbose_name='更新时间')),
                ('article', models.ForeignKey(db_comment='该版本所属的文章主记录。', on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='knowledge.article', verbose_name='所属文章')),
                ('created_by', models.ForeignKey(db_comment='创建该版本的用户，也是自审限制的作者依据。', on_delete=django.db.models.deletion.PROTECT, related_name='created_article_versions', to=settings.AUTH_USER_MODEL, verbose_name='版本创建人')),
                ('submitted_by', models.ForeignKey(blank=True, db_comment='将该版本提交审核的用户；草稿阶段为空。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_article_versions', to=settings.AUTH_USER_MODEL, verbose_name='提交审核人')),
            ],
            options={
                'verbose_name': '文章版本',
                'verbose_name_plural': '文章版本',
                'db_table': 'kb_article_version',
                'db_table_comment': '知识文章版本，保存正文、摘要、适用范围和审核状态快照。',
                'ordering': ('article_id', '-version_no'),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='current_published_version',
            field=models.ForeignKey(blank=True, db_comment='当前对员工展示的已发布版本；首版发布前允许为空。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_pointer_articles', to='knowledge.articleversion', verbose_name='当前发布版本'),
        ),
        migrations.AddField(
            model_name='article',
            name='latest_working_version',
            field=models.ForeignKey(blank=True, db_comment='最新草稿、待审核或已驳回版本；没有工作版本时为空。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='working_pointer_articles', to='knowledge.articleversion', verbose_name='最新工作版本'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(db_comment='知识分类主键，使用 UUID。', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='分类 ID')),
                ('code', models.CharField(db_comment='不可随分类名称变化的稳定业务分类编码。', max_length=30, verbose_name='分类编码')),
                ('name', models.CharField(db_comment='面向员工展示的业务分类名称。', max_length=100, verbose_name='分类名称')),
                ('icon', models.CharField(blank=True, db_comment='前端使用的图标名称或受控资源标识。', max_length=100, verbose_name='图标')),
                ('sort_order', models.PositiveIntegerField(db_comment='同层级分类的显示顺序，数值越小越靠前。', default=0, verbose_name='排序值')),
                ('is_active', models.BooleanField(db_comment='控制分类是否可用于新建知识和前台导航。', db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='分类首次创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='分类最后更新时间。', verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, db_comment='父级分类；空值表示一级分类。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='knowledge.category', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '知识分类',
                'verbose_name_plural': '知识分类',
                'db_table': 'kb_category',
                'db_table_comment': '知识业务分类，支持父子层级和排序。',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(db_comment='文章当前所属的主要业务分类。', on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='knowledge.category', verbose_name='业务分类'),
        ),
        migrations.CreateModel(
            name='KnowledgeSpace',
            fields=[
                ('id', models.UUIDField(db_comment='知识空间主键，使用 UUID。', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='空间 ID')),
                ('code', models.SlugField(db_comment='稳定的知识空间编码，用于程序识别。', unique=True, verbose_name='空间编码')),
                ('name', models.CharField(db_comment='知识空间的中文显示名称。', max_length=100, verbose_name='空间名称')),
                ('description', models.TextField(blank=True, db_comment='知识空间用途与内容边界说明。', default='', verbose_name='说明')),
                ('space_type', models.CharField(choices=[('employee', '员工知识空间'), ('it_internal', 'IT 内部知识空间'), ('admin', '管理员空间')], db_comment='空间类型：员工、IT 内部或管理员空间。', db_index=True, max_length=20, verbose_name='空间类型')),
                ('default_audience_policy', models.CharField(choices=[('all_employees', '全员'), ('restricted', '指定范围'), ('it_only', '仅 IT')], db_comment='在文章未明确覆盖时使用的默认内容受众策略。', default='restricted', max_length=20, verbose_name='默认受众策略')),
                ('is_active', models.BooleanField(db_comment='控制知识空间是否允许继续创建和展示内容。', db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='知识空间首次创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='知识空间最后更新时间。', verbose_name='更新时间')),
                ('owner', models.ForeignKey(db_comment='负责该知识空间管理与内容质量的用户。', on_delete=django.db.models.deletion.PROTECT, related_name='owned_knowledge_spaces', to=settings.AUTH_USER_MODEL, verbose_name='空间负责人')),
            ],
            options={
                'verbose_name': '知识空间',
                'verbose_name_plural': '知识空间',
                'db_table': 'kb_knowledge_space',
                'db_table_comment': '知识空间，定义内容管理边界与默认受众策略。',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='category',
            name='space',
            field=models.ForeignKey(db_comment='分类所属知识空间。', on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='knowledge.knowledgespace', verbose_name='知识空间'),
        ),
        migrations.AddField(
            model_name='article',
            name='space',
            field=models.ForeignKey(db_comment='文章所属知识空间，决定内容管理边界。', on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='knowledge.knowledgespace', verbose_name='知识空间'),
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.UUIDField(db_comment='审核记录主键，使用 UUID。', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='审核记录 ID')),
                ('review_type', models.CharField(choices=[('content_review', '发布审核'), ('periodic_review', '到期复审'), ('emergency_review', '紧急审核')], db_comment='发布审核、到期复审或紧急审核。', default='content_review', max_length=20, verbose_name='审核类型')),
                ('decision', models.CharField(choices=[('approved', '审核通过'), ('rejected', '审核驳回'), ('continue_valid', '继续有效'), ('revision_required', '需要修订'), ('offline', '立即下架')], db_comment='审核通过、驳回、继续有效、需要修订或立即下架。', max_length=20, verbose_name='审核结论')),
                ('comment', models.TextField(blank=True, db_comment='审核意见；驳回、要求修订或下架时必须填写。', verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, db_comment='审核结论形成时间。', verbose_name='审核时间')),
                ('article_version', models.ForeignKey(db_comment='本次审核或复审所针对的具体文章版本。', on_delete=django.db.models.deletion.PROTECT, related_name='review_records', to='knowledge.articleversion', verbose_name='文章版本')),
                ('reviewer', models.ForeignKey(db_comment='执行审核并对结论负责的用户。', on_delete=django.db.models.deletion.PROTECT, related_name='article_review_records', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '审核记录',
                'verbose_name_plural': '审核记录',
                'db_table': 'kb_review_record',
                'db_table_comment': '知识版本审核与复审记录，保留审核人、结论、意见和时间。',
                'ordering': ('-reviewed_at',),
            },
        ),
        migrations.CreateModel(
            name='ArticleAudience',
            fields=[
                ('id', models.UUIDField(db_comment='文章受众关系主键，使用 UUID。', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='受众记录 ID')),
                ('audience_type', models.CharField(choices=[('all_employees', '全员'), ('department', '指定部门'), ('user_group', '指定用户组'), ('user', '指定用户'), ('it_only', '仅 IT')], db_comment='全员、指定部门、指定用户组、指定用户或仅 IT。', max_length=20, verbose_name='受众类型')),
                ('effect', models.CharField(choices=[('allow', '允许'), ('deny', '拒绝')], db_comment='允许或显式拒绝；拒绝规则优先于允许规则。', default='allow', max_length=10, verbose_name='规则效果')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='受众规则创建时间。', verbose_name='创建时间')),
                ('article', models.ForeignKey(db_comment='受该受众规则控制的文章。', on_delete=django.db.models.deletion.PROTECT, related_name='audience_rules', to='knowledge.article', verbose_name='文章')),
                ('created_by', models.ForeignKey(db_comment='创建或配置该受众规则的用户。', on_delete=django.db.models.deletion.PROTECT, related_name='created_article_audience_rules', to=settings.AUTH_USER_MODEL, verbose_name='规则创建人')),
                ('department', models.ForeignKey(blank=True, db_comment='受众类型为指定部门时的部门对象。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_audience_rules', to='accounts.department', verbose_name='指定部门')),
                ('user', models.ForeignKey(blank=True, db_comment='受众类型为指定用户时的平台用户。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_audience_rules', to=settings.AUTH_USER_MODEL, verbose_name='指定用户')),
                ('user_group', models.ForeignKey(blank=True, db_comment='受众类型为指定用户组时的内容受众用户组。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_audience_rules', to='accounts.usergroup', verbose_name='指定用户组')),
            ],
            options={
                'verbose_name': '文章受众规则',
                'verbose_name_plural': '文章受众规则',
                'db_table': 'kb_article_audience',
                'db_table_comment': '文章内容受众规则，系统操作角色不得写入本表。',
                'ordering': ('article_id', 'audience_type', 'effect'),
                'indexes': [models.Index(fields=['article', 'audience_type', 'effect'], name='kb_aud_article_type_idx'), models.Index(fields=['audience_type', 'department'], name='kb_aud_type_dept_idx'), models.Index(fields=['audience_type', 'user_group'], name='kb_aud_type_group_idx'), models.Index(fields=['audience_type', 'user'], name='kb_aud_type_user_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('audience_type__in', ('all_employees', 'it_only')), ('department__isnull', True), ('effect', 'allow'), ('user__isnull', True), ('user_group__isnull', True)), models.Q(('audience_type', 'department'), ('department__isnull', False), ('user__isnull', True), ('user_group__isnull', True)), models.Q(('audience_type', 'user_group'), ('department__isnull', True), ('user__isnull', True), ('user_group__isnull', False)), models.Q(('audience_type', 'user'), ('department__isnull', True), ('user__isnull', False), ('user_group__isnull', True)), _connector='OR'), name='kb_aud_target_shape_ck'), models.UniqueConstraint(condition=models.Q(('audience_type', 'all_employees')), fields=('article',), name='kb_aud_all_uniq'), models.UniqueConstraint(condition=models.Q(('audience_type', 'it_only')), fields=('article',), name='kb_aud_it_uniq'), models.UniqueConstraint(condition=models.Q(('audience_type', 'department')), fields=('article', 'department', 'effect'), name='kb_aud_dept_uniq'), models.UniqueConstraint(condition=models.Q(('audience_type', 'user_group')), fields=('article', 'user_group', 'effect'), name='kb_aud_group_uniq'), models.UniqueConstraint(condition=models.Q(('audience_type', 'user')), fields=('article', 'user', 'effect'), name='kb_aud_user_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='articleversion',
            index=models.Index(fields=['article', 'status'], name='kb_ver_article_status_idx'),
        ),
        migrations.AddIndex(
            model_name='articleversion',
            index=models.Index(fields=['status', 'submitted_at'], name='kb_ver_status_submit_idx'),
        ),
        migrations.AddIndex(
            model_name='articleversion',
            index=models.Index(fields=['created_by', 'created_at'], name='kb_ver_creator_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='articleversion',
            constraint=models.UniqueConstraint(fields=('article', 'version_no'), name='kb_ver_article_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='articleversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('draft', 'in_review', 'rejected'))), fields=('article',), name='kb_ver_working_uniq'),
        ),
        migrations.AddConstraint(
            model_name='articleversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('article',), name='kb_ver_published_uniq'),
        ),
        migrations.AddConstraint(
            model_name='articleversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_no__gt', 0)), name='kb_ver_no_positive_ck'),
        ),
        migrations.AddConstraint(
            model_name='articleversion',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), models.Q(('submitted_by__isnull', False), ('submitted_at__isnull', False)), _connector='OR'), name='kb_ver_submitted_ck'),
        ),
        migrations.AddConstraint(
            model_name='articleversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='kb_ver_published_at_ck'),
        ),
        migrations.AddIndex(
            model_name='knowledgespace',
            index=models.Index(fields=['space_type', 'is_active'], name='kb_space_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['space', 'parent', 'sort_order'], name='kb_cat_space_parent_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('space', 'code'), name='kb_cat_space_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['space', 'article_status'], name='kb_art_space_status_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'article_status'], name='kb_art_cat_status_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['owner', 'review_due_at'], name='kb_art_owner_due_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['article_status', 'effective_at'], name='kb_art_status_effect_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewrecord',
            index=models.Index(fields=['article_version', 'reviewed_at'], name='kb_review_version_time_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewrecord',
            index=models.Index(fields=['reviewer', 'reviewed_at'], name='kb_review_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewrecord',
            index=models.Index(fields=['decision', 'reviewed_at'], name='kb_review_decision_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision__in', ('rejected', 'revision_required', 'offline')), _negated=True), models.Q(('comment', ''), _negated=True), _connector='OR'), name='kb_review_comment_ck'),
        ),
    ]
