# Generated by Django 5.2.17 on 2026-09-04 15:20

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='kb_no',
            field=models.CharField(db_comment='全局唯一且不可变的知识编号，格式为 KB-000001。', editable=False, max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='知识编号必须符合 KB-000001 格式。', regex='^KB-[0-9]{6}$')], verbose_name='知识编号'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('kb_no__regex', '^KB-[0-9]{6}$')), name='kb_article_kb_no_format_ck'),
        ),
    ]
