# Generated by Django 5.2.17 on 2026-09-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_alter_article_kb_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgespace',
            name='default_audience_policy',
            field=models.CharField(choices=[('all_employees', '全员'), ('restricted', '指定范围'), ('it_only', '仅 IT')], db_comment='仅供新建文章赋初值，读取不回退，修改默认值不改变已有文章。', default='restricted', max_length=20, verbose_name='默认受众策略'),
        ),
    ]
