# Generated by Django 5.2.17 on 2026-10-05 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0003_space_audience_policy_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeNumberCounter",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        db_comment="固定为 1 的全局知识编号计数器单例主键。",
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "next_value",
                    models.PositiveIntegerField(
                        db_comment="下一次可分配 KB 数字；超过六位时由 Service 报告耗尽。",
                        default=1,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="计数器最后更新时间。"),
                ),
            ],
            options={
                "db_table": "kb_number_counter",
                "db_table_comment": "全局 KB 编号计数器；不得作为人工维护入口。",
            },
        ),
        migrations.RemoveConstraint(
            model_name="articleversion",
            name="kb_ver_working_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="articleversion",
            name="kb_ver_submitted_ck",
        ),
        migrations.AddField(
            model_name="articleversion",
            name="lock_version",
            field=models.PositiveIntegerField(
                db_comment="草稿写入的乐观锁版本号；后续保存 Service 必须显式比较并递增。",
                default=1,
                editable=False,
                verbose_name="乐观锁版本",
            ),
        ),
        migrations.AddField(
            model_name="articleversion",
            name="restored_from_version",
            field=models.ForeignKey(
                blank=True,
                db_comment="历史恢复创建新草稿时记录的同文章来源版本。",
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="restored_descendants",
                to="knowledge.articleversion",
                verbose_name="恢复来源版本",
            ),
        ),
        migrations.AlterField(
            model_name="articleversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("saved", "已保存"),
                    ("in_review", "待审核"),
                    ("rejected", "已驳回"),
                    ("published", "已发布"),
                    ("superseded", "已替代"),
                ],
                db_comment="版本状态：草稿、已保存、待审核、已驳回、已发布或已替代。",
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="版本状态",
            ),
        ),
        migrations.AddConstraint(
            model_name="articleversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "draft")),
                fields=("article",),
                name="kb_ver_working_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="articleversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("draft", "saved")),
                    models.Q(("submitted_by__isnull", False), ("submitted_at__isnull", False)),
                    _connector="OR",
                ),
                name="kb_ver_submitted_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="articleversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("lock_version__gt", 0)), name="kb_ver_lock_positive_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgenumbercounter",
            constraint=models.CheckConstraint(
                condition=models.Q(("id", 1)), name="kb_counter_singleton_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgenumbercounter",
            constraint=models.CheckConstraint(
                condition=models.Q(("next_value__gt", 0)), name="kb_counter_next_positive_ck"
            ),
        ),
    ]
